# Screen dimensions
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Asteroid settings
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPAWN_RATE = 1.0
ASTEROID_MIN_SPAWN_RATE = 0.2

# Player settings
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_ACCELERATION = 400
PLAYER_MAX_SPEED = 400
PLAYER_IMMUNITY_TIME = 2.0

# Shot settings
PLAYER_SHOOT_SPEED = 500
SHOT_RADIUS = 5

# Explosion settings
EXPLOSION_MIN_SPEED = 100
EXPLOSION_MAX_SPEED = 300
EXPLOSION_PARTICLE_LIFETIME = 1.5
EXPLOSION_NUM_PARTICLES = 20

# Scoring and bonuses
EXTRA_LIFE_SCORE = 200
SHIELD_BONUS_SCORE = 150
SHIELD_IMMUNITY_TIME = 0.5